### ISSUE TITLE
Style of the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-thewoodcraft#9]
For the different section headings, you use different fonts, weight, casing, and size. Could you tell me why please? 

I would imagine having every heading be the same font, size, weight, and casing be the same would be ideal for consistency's sake. 

due:
1-4-16   4p

**Comment by jperez4509** [comment]
@rodneystrong The Woodcraft site is overall very modern, this is the reason why I am using a sans-serif font throughout. However, The Woodcraft logo uses a script font. I used a similar script font for the jumbotron h1 to bring in the script font from the logo. I did not use it for the rest of the site because I felt it became redundant and lost the appeal if it was over used. The reason why I decided to use the script font on the 'About Us' section is because that section was originally towards the bottom of the page and I felt it tied in the top of the page, while also adding some spark to a very simple section.

With such a small and simple site like The Woodcraft I feel using the same weight, casing and size for all section headings it becomes boring and redundant. That is why I made them all look different yet the same. They all seem related without being twins. I personally think the different headings gives the site more appeal.

**Comment by rodneystrong** [comment]
I agree on your points about the sans-serif and also uses serif to tie the logo to the rest of the site. However I'd like to challenge you on your reasons for breaking consistency. Here's why:
http://somup.com/cDVfrl3KB

Please post a response here.

**Comment by jperez4509** [comment]
@rodneystrong I agree on most points you made and I really like your examples. I have noticed that many of my designs have fallen to the same design where I separate them using a horizontal line or color. I have been researching on other design models myself. I have also noticed that I am not consistent with the colors, fonts size, weight I use on most of my sites and I need to create more global styles to make the site always look the same and save myself sometime. I have fallen a victim to always wanting to make individual sections 'unique'.

<p style="text-decoration: line-through;">However, in the 'About Us' section I still feel the script font is needed. It is needed because that section will look so plain with out some styling. Maybe we remove the script but then I think something has to be added.</p> Actually I just changed the font family and I don't hate it.

**Comment by rodneystrong** [comment]
Haha, it's not so much that I didn't want you to use the serif font for the headings, it's that I wanted you to continuously use the serif font for the rest of the headings to maintain consistency. 

Did you try a version where all the headings were "Satisfy" ?

**Comment by jperez4509** [comment]
@rodneystrong No I did not try a version where the headings were 'Satisfy'. The reason for that is because I feel that if I change the headings to 'Satisfy' the site will look to playful. 'Lato' is a sans-serif which gives the site a more modern and professional look.

*note: that I did not change the heading on gh-pages, I just changed it using inspect element to get the screenshot*
